// <auto-generated />
namespace DL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddUsersBooks : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddUsersBooks));
        
        string IMigrationMetadata.Id
        {
            get { return "201908261349185_AddUsersBooks"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
